version: '3.2'

services:
  bitcoin:
    extends:
      file: min-docker-compose.yml
      service: bitcoin
  postgres:
    extends:
      file: min-docker-compose.yml
      service: postgres
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    stop_grace_period: 5s
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: devnet
      MONGO_INITDB_ROOT_PASSWORD: devnet
      MONGO_INITDB_DATABASE: devnet
  mempool-db:
    image: mariadb:10.5.21
    container_name: mempool-db
    stop_grace_period: 5s
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: "mempool"
      MYSQL_USER: "mempool"
      MYSQL_PASSWORD: "mempool"
      MYSQL_ROOT_PASSWORD: "admin"
  miner:
    image: miner:latest
    container_name: miner
    stop_grace_period: 5s
    build:
      context: ./miner/docker
    depends_on:
      - bitcoin
    environment:
      INIT_BTC_BLOCKS: 200
      BTC_BLOCK_GEN_TIME: 10
  stacks:
    extends:
      file: min-docker-compose.yml
      service: stacks
  stacks-api:
    extends:
      file: min-docker-compose.yml
      service: stacks-api
  stacks-explorer:
    image: stacks-explorer
    container_name: stacks-explorer
    stop_grace_period: 5s
    build:
      context: ./stacks-explorer/docker
      args:
        STACKS_EXPLORER_VERSION: 'v1.119.0'
        GIT_URI: https://github.com/hirosystems/explorer.git
        GIT_BRANCH: v1.119.0
    ports:
      - 3020:3000
    depends_on:
      - bitcoin
      - stacks
      - stacks-api
      - postgres
    environment:
      - NEXT_PUBLIC_MAINNET_API_SERVER=http://127.0.0.1:3999
  electrs:
    extends:
      file: min-docker-compose.yml
      service: electrs
  sbtc:
    image: sbtc:latest
    container_name: sbtc
    stop_grace_period: 5s
    build:
      context: ./../
      dockerfile: ./devenv/sbtc/docker/Dockerfile
    depends_on:
      - bitcoin
      - stacks
      - stacks-explorer
      - stacks-api
      - mempool-web
      - miner
    environment:
      RUST_BACKTRACE: 1
    volumes:
      - $PWD/sbtc/docker/config.json:/romeo/config.json
  sbtc-bridge-api:
    image: sbtc-bridge-api:latest
    container_name: sbtc-bridge-api
    stop_grace_period: 5s
    build:
      context: ./sbtc-bridge-api/docker
      args:
        BRIDGE_GIT_URI: https://github.com/stacks-network/sbtc-bridge-api.git
        BRIDGE_GIT_BRANCH: main
    depends_on:
      - bitcoin
      - miner
      - stacks
      - stacks-api
      - mempool-web
      - postgres
      - stacks-explorer
      - mongodb
      - sbtc
    ports:
      - 3010:3010
    environment:
      NODE_ENV: dev
      btcNode: bitcoin:18443
      btcRpcUser: devnet
      btcRpcPwd: devnet
      network: testnet
      bitcoinExplorerUrl: http://mempool-web:8083
      stacksExplorerUrl: http://stacks-explorer:3020
      stacksApi: http://stacks-api:3999
      sbtcContractId: ST1PQHQKV0RJXZFY1DGX8MNSNYVE3VGZJSRTPGZGM.asset
      mongoDbUrl: mongodb
      mongoDbName: devnet
      mongoUser: devnet
      mongoPwd: devnet
  sbtc-bridge-web:
    image: sbtc-bridge-web:latest
    container_name: sbtc-bridge-web
    stop_grace_period: 5s
    build:
      context: ./sbtc-bridge-web/docker
    depends_on:
      - bitcoin
      - stacks
      - stacks-explorer
      - stacks-api
      - mempool-web
      - miner
      - sbtc
      - sbtc-bridge-api
    ports:
      - 8080:8080
  mempool-web:
    image: mempool/frontend:latest
    container_name: mempool-web
    stop_grace_period: 5s
    depends_on:
      - mempool-api
      - mempool-db
    user: "1000:1000"
    restart: on-failure
    ports:
      - 8083:8083
    environment:
      FRONTEND_HTTP_PORT: "8083"
      BACKEND_MAINNET_HTTP_HOST: "mempool-api"
    command: "./wait-for mempool-db:3306 --timeout=720 -- nginx -g 'daemon off;'"
  mempool-api:
    image: mempool/backend:latest
    container_name: mempool-api
    stop_grace_period: 5s
    depends_on:
      - electrs
      - mempool-db
    user: "1000:1000"
    restart: on-failure
    ports:
      - 8999:8999
    environment:
      # Connect to electrs host
      MEMPOOL_BACKEND: "electrum"
      ELECTRUM_HOST: "electrs"
      ELECTRUM_PORT: "60401"
      ELECTRUM_TLS_ENABLED: "false"
      # Connect to bitcoin rpc
      CORE_RPC_HOST: "bitcoin"
      CORE_RPC_PORT: "18443"
      CORE_RPC_USERNAME: "devnet"
      CORE_RPC_PASSWORD: "devnet"
      DATABASE_ENABLED: "true"
      DATABASE_HOST: "mempool-db"
      DATABASE_DATABASE: "mempool"
      DATABASE_USERNAME: "mempool"
      DATABASE_PASSWORD: "mempool"
      STATISTICS_ENABLED: "true"
    command: "./wait-for-it.sh mempool-db:3306 --timeout=720 --strict -- ./start.sh"
