[project]
name = 'asset-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[contracts.asset]
path = 'contracts/asset.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini]
path = 'contracts/clarity-bitcoin-mini.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini-deploy]
path = 'contracts/clarity-bitcoin-mini-deploy.clar'
clarity_version = 2
epoch = 2.4

[contracts.sbtc-send-many]
path = 'contracts/sbtc-send-many.clar'
clarity_version = 2
epoch = 2.4

[contracts.asset_test]
path = 'tests/asset_test.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini_test]
path = 'tests/clarity-bitcoin-mini_test.clar'
clarity_version = 2
epoch = 2.4


[contracts.sbtc-send-many_test]
path = 'tests/sbtc-send-many_test.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
