[project]
name = 'asset-contract'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'
[contracts.asset]
path = 'contracts/asset.clar'
clarity_version = 2
epoch = 2.4

[contracts.clarity-bitcoin-mini]
path = 'contracts/clarity-bitcoin-mini.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
